services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./dbdata:/var/lib/mysql
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:ro
